services:
  frontend:
    build:
      context: ./trackmate-front
      dockerfile: Dockerfile
    container_name: trackmate_frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_BASE_API_URL: "http://mast23mc.net/api/"
      NEXT_PUBLIC_TOKEN: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIxQGV4YW1wbGUuY29tIiwiZXhwIjo0OTA4NTA4Nzk3LCJzdWIiOiIzYThjNGMxYy1mNDNkLTQ1ZjItOGE2My02NjcxNTNkOTgxNDgifQ.n_wALU5AnKfpAaUbKC_n2c4PUglLqkQUGuUbFePKMGk"
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3401:3401"
    # volumes:
    #   - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0
    container_name: trackmate_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: track
      MYSQL_PASSWORD: tracktrack
    ports:
      - "3300:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  db_data: